#!/bin/sh

BRANCH=$(git rev-parse --abbrev-ref HEAD)
REGEX="^(main|((feat|fix|docs|chore|refactor|release|test|hotfix)\/.+))$"

if ! echo "$BRANCH" | grep -Eq "$REGEX"; then
  echo "Your commit was rejected due to invalid branch name: '$BRANCH'"
  echo "Please rename your branch to follow one of the accepted formats:"
  echo "  - feat/*, fix/*, docs/*, chore/*, refactor/*, release/*, test/*, hotfix/*"
  exit 1
fi
